### PR TITLE
Bugfix: Do not allocate spi_port on the Stack - EXC_BAD_ACCESS on OS X

### PR DESCRIPTION
**Pull request by nwoolls**

### CODE REVIEW

**Comment by luke-jr** [comment]
Please make the function names unique (eg, dname_fname). I realise it's mostly safe since they're static, but just in case...

**Comment by nwoolls** [comment]
Thanks good call still not used to C - this is going to take a while!

**Comment by nwoolls** [comment]
Done.

**Comment by nwoolls** [comment]
Comments updated

**Pull request merged**
