### PR TITLE
Translated README to MarkDown format

### PR DESCRIPTION
**Pull request by suranyami**
It reads better on the Github repo landing page. 
It's a little thing, and entirely optional, but I found it useful.

Feel free to ignore it, but use it if you find it useful.

### CODE REVIEW

**Comment by luke-jr** [comment]
Is it possible to generate the README plaintext from this?

**Comment by suranyami** [comment]
Initial investigation says 'yes'. Just gonna check if there's a way to do it from a clean linux install. (i.e. doesn't depend on installing some other lib just for this).

**Comment by luke-jr** [comment]
I've not found a simple way to do MD->TXT - other dependencies don't matter (I'll just make it part of the pre-build process).

**Comment by suranyami** [comment]
# I did a bit of hunting on the weekend and couldn't find an easy way either.

**Comment by yskywalker** [comment]
Why not include a markdown and a plain text version.  I think it's worth the extra work of keeping both updated because being able to add formatting makes a big difference in the clarity, simplicity and attractiveness of the repo main page.

**Comment by luke-jr** [comment]
This is now obsolete; please feel free to reopen with an updated version if we can autogenerate txt from md.

**Pull request closed without merging**
