### PR TITLE
Adding a spec file for building RPMs

### PR DESCRIPTION
**Pull request by funzoneq**
http://vps.us.freshway.biz/CentOS-6-Production-x86_64/RPMS.bfgminer/

### CODE REVIEW

**Comment by luke-jr** [comment]
But not even 3.0.0 has been released yet :/

**Comment by luke-jr** [comment]
Can you fix the version to 2.99.2 for now?

**Comment by funzoneq** [comment]
I updated the spec file to be on 3.0.2 for real this time :+1:

**Comment by luke-jr** [comment]
In the meantime, Christian Berendt has contributed a SuSE .spec file. I can still merge this (but moving it to a packaging/redhat/ directory), but maybe it would be a good idea to try to get a .spec that works well with both systems?

**Comment by luke-jr** [comment]
Still alive?

**Comment by luke-jr** [comment]
Feel free to open a new pullreq if you decide to revive this...

**Pull request closed without merging**
