### PR TITLE
Added get_api_extra_device_status for 'devs' request in metabank driver: Slot, Clock Bits, Temperature, Voltage.

### PR DESCRIPTION
**Pull request by Viktor-KN**

### CODE REVIEW

**Comment by luke-jr** [comment]
Please store temperatures on cgpu_info.temp instead.

**Comment by Viktor-KN** [comment]
Done.

**Comment by luke-jr** [comment]
This is reporting 35.2 C for both slots, but I'd expect much hotter from physical touch...

I think i2c is not threadsafe, so metabank_get_stats will need to use a mutex possibly. But maybe I can make it call from the same thread - will get back to you on that :)

**Comment by Viktor-KN** [comment]
It reporting from sensor on the board, not from chips itself. Sensor is located in not very good place... But this is all we have...

**Comment by luke-jr** [comment]
Thanks

**Pull request merged**
