### PR TITLE
Increase stratum proxy difficulty to 16 for SHA256 clients.

### PR DESCRIPTION
**Pull request by xrobau**
Difficulty of 1 is too little for even entry level 100gh hardware now.. And with 'entry level' moving to 500gh over the next few months, this should do for a while.

### CODE REVIEW

**Comment by luke-jr** [comment]
This doesn't check that the upstream difficulty isn't < 16. Maybe it should also be configurable?

**Comment by xrobau** [comment]
That's deliberate.  Any pool that's asking for difficulty 1 shares with more than 100gh or so pointed at it is going to get flooded (difficulty 1 @ 100gh = about 30 shares per second). By filtering them to difficulty 16, it doesn't destroy the pool quite as badly, and gives it a chance to realise that it should increase the difficulty quickly.

I'm working on the assumption that people who are using the stratum proxy are using it for significant hashrates.  This may be wrong if people are using it with a couple of 1gh USB miners.  You know best! 8)

**Comment by luke-jr** [comment]
That's the pool's problem - not sure we should make a bug to help them deal with it :)

**Comment by luke-jr** [comment]
Please help test and review #486

**Pull request closed without merging**
