### PR TITLE
Use libbase58 for base58 encoding/decoding

### PR DESCRIPTION
**Pull request by luke-jr**

### CODE REVIEW

**Comment by 4tar** [comment]
Built ok on Linux/gcc, didn't check on other platforms like MinGW/OpenWrt.

**Comment by luke-jr** [comment]
@nwoolls Can you test Mac/Windows native builds?

**Comment by nwoolls** [comment]
@luke-jr works on Mac OS X, does not work on Windows:

```
Making all in ccan.bfg
make[2]: Entering directory `/home/Nathanial/bfgminer/ccan.bfg'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/Nathanial/bfgminer/ccan.bfg'
Making all in libbase58
make[2]: Entering directory `/home/Nathanial/bfgminer/libbase58'
make[2]: *** No rule to make target `all'.  Stop.
make[2]: Leaving directory `/home/Nathanial/bfgminer/libbase58'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/Nathanial/bfgminer'
make: *** [all] Error 2
```

**Comment by nwoolls** [comment]
@luke-jr is there a new dependency?

```
Nathanial@Nate-Win8-64bit ~/bfgminer/libbase58
$ ./autogen.sh
autoreconf-2.68: Entering directory `.'
autoreconf-2.68: configure.ac: not using Gettext
autoreconf-2.68: running: aclocal --force
configure.ac:34: warning: macro `AM_PATH_LIBGCRYPT' not found in library
autoreconf-2.68: configure.ac: tracing
autoreconf-2.68: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: Consider adding `AC_CONFIG_MACRO_DIR([m4])' to configure.ac and
libtoolize: rerunning libtoolize, to keep the correct libtool macros in-tree.
libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:34: warning: macro `AM_PATH_LIBGCRYPT' not found in library
autoreconf-2.68: running: /mingw/bin/autoconf-2.68 --force
configure.ac:34: error: possibly undefined macro: AM_PATH_LIBGCRYPT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:38: error: possibly undefined macro: AC_MSG_ERROR
autoreconf-2.68: /mingw/bin/autoconf-2.68 failed with exit status: 1
```

**Comment by nwoolls** [comment]
```
autoreconf -i
configure.ac:13: require Automake 1.12, but have 1.11.1
```

Automake 1.11 is the newest for MinGW :(

**Comment by nwoolls** [comment]
I changed configure.ac to allow Automake 1.11 which allowed autoreconf -i to succeed. augogen.sh still fails with the output above.

Additionally, ./configure fails with:

```
...
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for strchr in -lws2_32... yes
./configure: line 11359: syntax error near unexpected token `,'
./configure: line 11359: `      AM_PATH_LIBGCRYPT(,'
```

**Pull request merged**
