### PR TITLE
opencl: Accept arbitrary kernel filenames, provided they specify a kernel interface somewhere in the source file

### PR DESCRIPTION
**Pull request by luke-jr**
File must include the string "kernel-interface:" followed by one of the known interface names

### CODE REVIEW

**Comment by nwoolls** [comment]
I love you man.

**Comment by OhGodAPet** [comment]
Thanks, Luke, for implementing my suggestion. I don't know if I could have done it.

**Comment by luke-jr** [comment]
Can someone please test this, perhaps with some of sgminer's kernel files? They should just work as-is...

**Comment by nwoolls** [comment]
I'm out of town again this week but will be happy to test when I get back.

**Pull request merged**
