### PR TITLE
Bugfix: zeusminer: icarus timing can lead to false positive Idle detection

### PR DESCRIPTION
**Pull request by nwoolls**

### CODE REVIEW

**Comment by luke-jr** [comment]
Huh? Why is that?

**Comment by nwoolls** [comment]
It causes the read_count to reach a point where the thread doesn't report in for 60 seconds, so BFGMiner reports it as idle.

**Comment by luke-jr** [comment]
Hm, should it be > 60 seconds? Maybe we should just have icarus reportin?

**Comment by luke-jr** [comment]
Actually, we should check scantime in icarus at least, and limit read_count to that too...

**Pull request merged**
