### PR TITLE
Add Difficulty adjustment countdown in terms of

### PR DESCRIPTION
**Pull request by TrooperT**
blocks remaining until next adjustment

### CODE REVIEW

**Comment by luke-jr** [comment]
This probably overflows the line for most terminals. Can we fit it nicer somehow? Also needs README updated.

**Comment by TrooperT** [comment]
will think of a two letter and update. 

but do you like the idea?

**Comment by luke-jr** [comment]
Sure. I wonder if it belongs after the block diff?

**Comment by TrooperT** [comment]
i agree. will move around. sorry in advance for so many commit changes. working from a mobile phone

**Comment by TrooperT** [comment]
there :)

**Comment by luke-jr** [comment]
How does this react if the block height is not known (maybe test with an old old altcoin)? ;)

**Comment by TrooperT** [comment]
was it a trick question? tested with no pool and --benchmark and no peculiar behavior

**Comment by luke-jr** [comment]
I'm not aware of an easy way to test this, short of setting up a test pool... meet me on IRC if you want me to run one for you.

Right now, this looks like:

```
Block: ...89a64718e19ffe25 Diff:1( 7.16Mh/s) TG:2016 Started:[18:11:53]
```

TG should probably just not be shown at all in this case, though.

Observe the current behaviour:

```
Unknown block height: Block: ...d24b1f3c64df2faf  Diff:1.79G (12.81Ph/s)  Started: [18:10:58]
Known   block height: Block: ...214dbffd #280331  Diff:1.79G (12.81Ph/s)  Started: [18:04:36]
```

**Comment by luke-jr** [comment]
@Taugeran ping?

**Comment by TrooperT** [comment]
closing for now. just had a nightmare spring to life IRL. barely keeping self together

**Comment by luke-jr** [comment]
:( hope things get better soon.

**Pull request closed without merging**
