### PR TITLE
Bfgminer 2.8.x

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by luke-jr** [comment]
Hi. What did you do to create this pull request?

**Comment by ghost** [comment]
I created a pull request

**Comment by luke-jr** [comment]
What was your goal in doing so?

**Comment by ghost** [comment]
Trying to pull an older version. I need it

**Comment by luke-jr** [comment]
try typing: git checkout bfgminer-2.8.x

**Comment by ghost** [comment]
Git checkout bfgminer-2.1.8

**Comment by ghost** [comment]
Didn't work

**Pull request closed without merging**
