### PR TITLE
Futurebit2 driver

### PR DESCRIPTION
**Pull request by jstefanop**

### CODE REVIEW

**Comment by fogoat** [comment]
When do you expect binaries with ml2 support to be available?

**Comment by jstefanop** [comment]
In the process of compiling binaries now.

**Comment by FiberFiber** [comment]
Hello jstefanop, I need contact to you!  In private messages....how can be please?

**Comment by mikeharpe** [comment]
Been using it since last night on an RPi2 with current OS. The only thing I've seen is that when I quit out of it I have to reboot the Pi or it won't reconnect to the pool again. Other than that it seems to work fine with my FutureBit Moonlander 2.

**Comment by jstefanop** [comment]
@FiberFiber same UN on bitcointalk/tele etc.

**Comment by FiberFiber** [comment]
@jstefanop Done, I sended to you a private menssenge in Bitcointalk,  please check it.
Thanks for your reply

**Pull request merged**
