### PR TITLE
Antminer U3 support

### PR DESCRIPTION
**Pull request by luke-jr**
Needs testing with:
AntMiner U1: BSD ~~Linux~~ Mac Windows
AntMiner U2: BSD Linux Mac Windows
AntMiner U3: BSD ~~Linux~~ Mac Windows
Block Erupter: BSD ~~Linux~~ Mac Windows
Cairnsmore1: BSD Linux Mac Windows
DualMiner scrypt: BSD Linux Mac Windows
DualMiner SHA2: BSD Linux Mac Windows
Icarus: BSD Linux Mac Windows
Lancelot: BSD Linux Mac Windows
ZeusMiner: BSD Linux Mac Windows

Please help test if you can!

Windows binaries: http://luke.dashjr.org/tmp/code/webisect/webisect.php?dobuild=icarus_ms

### CODE REVIEW

**Comment by Blackbird17k** [comment]
Is this merge in 5.1.0?

**Comment by luke-jr** [comment]
No, it will be 5.2.0

**Comment by Blackbird17k** [comment]
How do I compile this pull and test?

**Comment by luke-jr** [comment]
What OS?

**Comment by Blackbird17k** [comment]
Raspbian.

**Comment by luke-jr** [comment]
```
git clone git://github.com/luke-jr/bfgminer
aptitude install build-essential autoconf automake libtool pkg-config libcurl4-gnutls-dev libjansson-dev uthash-dev libncursesw5-dev libudev-dev libusb-1.0-0-dev libevent-dev libmicrohttpd-dev hidapi
cd bfgminer
./autogen.sh
./configure
make
./bfgminer ...
```

**Comment by Blackbird17k** [comment]
Autogen doesn't work. I'm confused. Is this how I compile this test version?

When I sudo apt-get install, it says unable to find package hidapi.

**Comment by Blackbird17k** [comment]
Hmm...tried something else.

Now it says unable to fetch in submodule path libblmaker. remote end hung up unexpectedly.

**Comment by Blackbird17k** [comment]
All resolved per our discussion in the bitcointalk.org thread.

**Comment by tort2014** [comment]
Ok, downloaded and will test it with the U3.

Will post results.

Thanks.

**Comment by fabulouspanda** [comment]
I realise this was merged in to main branch, so I've compiled it for a beta version of MacMiner (lots of Mac users with U3! Must like the shiny new form factor…)

Anyway, based on a user report (don't have a test device) I'm informed this version seems to struggle with antminer U2 - causing bfgminer to stop.

Should U2 and U3 both be setup the same way e.g. -S antminer:all ? And do the voltage/frequency settings differ, at a glance it seems voltage is a new addition for the U3 support in the driver

**Comment by luke-jr** [comment]
Yes, but I don't have a U2 for testing, so no idea what's up with that...

**Comment by Blackbird17k** [comment]
I'm running U1, U2, and U3 simultaneously. Compiled on a Pi.

**Comment by fabulouspanda** [comment]
OK, I'm going to try to get more information from the user. I know that my BFL Jalapeño that developed a fault caused the same bfgminer shutdown every 10 mins so possibly it's just a HW issue. Will update if I can clarify. Thanks for your swift responses!

**Comment by jameshilliard** [comment]
FYI U2 is just a U1 capable of a slightly higher clock speed.

**Comment by fabulouspanda** [comment]
re Mac OS apparently the version of bfgminer I compiled about a week ago gets ~25% better speeds from the U2s than earlier versions

That said the one U3 a user I'm in touch with has to test only gets around 36GH/s and restarts itself randomly and connects with a new device id (incrementally higher number at /dev/cu.SLAB_USBtoUART*)

Hard to say whether that's a manufacturing defect from what little I've heard about the U3s and the test sample size of 1, but maybe it lines up with the Linux experience.

**Pull request merged**
