### PR TITLE
Fix hung gridseed

### PR DESCRIPTION
**Pull request by gades**
Fix bug #501

### CODE REVIEW

**Comment by nwoolls** [comment]
This is going to re-init each GridSeed device for every 10 seconds that they do not find a nonce. This isn't really desirable as:

a) It is reinitializing them when it doesn't need to
b) It is not taking into account pool difficulty, rather always using the same duration

As I mentioned in https://github.com/luke-jr/bfgminer/issues/501 we are improving the watchdog in BFGMiner to find these sorts of things and reinit the device.

**Comment by gades** [comment]
This temporarily solved my problem

**Comment by gades** [comment]
problem is not solved ....

**Comment by nwoolls** [comment]
https://github.com/nwoolls/bfgminer/commit/96cd94410bc020f52981a8871b7f065aeed5e8bd

This is the code I'm testing now.

**Comment by nwoolls** [comment]
@gades try merging both of these commits, this solution seems to work for me:

https://github.com/nwoolls/bfgminer/commit/b0531a6c2908a884b62b8b57740c495adf90ff4c
https://github.com/nwoolls/bfgminer/commit/c1ea3f5201c09751e26f753027c592145e1762d0

Would love to hear how it works for you.

**Comment by tsunam** [comment]
@nwoolls I can confirm that with two dualminers that I have which had the above issue were successfully re-enabled automatically as part of the watchdog with your above commits.

**Comment by nwoolls** [comment]
@tsunam that's great news. I just saw a 3rd confirmed instance of my DMU getting restarted and getting shares after so I think this looks pretty good.

**Comment by nwoolls** [comment]
Also if you run with --verbose you can get a live output of each chip.

**Comment by nwoolls** [comment]
@gades have you had a chance to test this? I'd love your feedback too. You can either merge the above commits or clone the following branch:

git clone -b feature\/reinit-hung-gridseed https://github.com/nwoolls/bfgminer.git

**Comment by gades** [comment]
Did not help: (Trying to make a merge code, as well as git clone-b feature \ / reinit-hung-gridseed https://github.com/nwoolls/bfgminer.git

Can see the log on dropbox:
https://www.dropbox.com/s/n6342cb1zk30jzb/bfg8.log

ps / Version 4.4.0 works without problems ...

**Comment by gades** [comment]
Hang-ups can emulate very fast on p2pool (happens every 5-20 minutes)

**Comment by nwoolls** [comment]
Use a regular pool please to reproduce this issue. I don't want to mix up pool issues with device issues.

I don't see anything wrong from your log. The ASICs were producing nonces in an acceptable time throughout the entire run.

Please try running on wemineltc.com and then see what the results are there with only that 1 pool (no backups, no failovers).

**Comment by nwoolls** [comment]
@gades along with trying a regular pool (wemineltc), please post your entire command line and arguments. From your log it looks like most / many of your shares are going to a local server.

**Comment by gades** [comment]
/opt/bin/bfgminer --scrypt --api-listen --api-network -L /home/hades/bfg8.log --verbose

and file:
{
"pools" : [
    {
        "url" : "stratum+tcp://127.0.0.1:9327",
        "user" : "iHades",
        "pass" : "some pass",
        "pool-priority" : "0"
    }
],
"api-listen" : true,
"api-mcast-port" : "4028",
"api-network" : true,
"api-port" : "4028",
"expiry" : "120",
"expiry-lp" : "3600",
"failover-switch-delay" : "300",
"log" : "20",
"no-pool-disable" : true,
"no-client-reconnect" : true,
"no-show-processors" : true,
"no-show-procs" : true,
"queue" : "1",
"quiet-work-updates" : true,
"quiet-work-update" : true,
"scan-time" : "60",
"scrypt" : true,
"skip-security-checks" : "0",
"submit-stale" : true,
"temp-hysteresis" : "3",
"request-diff" : 100,
"shares" : 0,
"kernel-path" : "/opt/share/bfgminer",
"scan" : [
    "gridseed:all"
],
"device" : [
    "gridseed",
    "gridseed",
    "gridseed"
],
"set-device" : [
    "OCL:fan=100",
    "OCL:thread-concurrency=16384",
    "OCL:kernel=psw",
    "OCL:intensity=13",
    "gridseed:clock=800"
]

**Comment by nwoolls** [comment]
@gades can you provide me with a public pool that exhibits the problem you are seeing?

Again I don't see anything wrong in the log file you posted. I'm trying p2pool myself and the only issue I see is that the diff is ridiculously high (for Scrypt) meaning finding shares will take a long time.

**Comment by gades** [comment]
List and debug after hung https://www.dropbox.com/s/r7j4aof335m913o/bfg11.log

Last share GSD2  [2014-07-15 19:35:41] Accepted 00b45d9f GSD 2au Diff 5m/2m
Last share GSD1 [2014-07-15 19:53:16] Accepted 0246c80b GSD 1bh Diff 1m/1m
GSD 0 - Do not hang up, but after a time may also hang.

Below is a sample of restart attempts. Maybe it makes sense to reopen the port / dev / ttyACMxx?

[2014-07-15 19:47:06] GSD 2ad: Attempting to restart
 [2014-07-15 19:47:06] GSD 2al: Attempting to restart
 [2014-07-15 19:47:06] GSD 2ao: Attempting to restart
 [2014-07-15 19:47:06] GSD 2ar: Attempting to restart
 [2014-07-15 19:47:06] GSD 2av: Attempting to restart
 [2014-07-15 19:47:06] GSD 2aw: Attempting to restart
 [2014-07-15 19:47:07] GSD 2ba: Attempting to restart
 [2014-07-15 19:47:07] GSD 2bl: Attempting to restart
 [2014-07-15 19:47:07] GSD 2bn: Attempting to restart
 [2014-07-15 19:47:23] GSD 2bk: Attempting to restart

**Comment by nwoolls** [comment]
@gades 

1) Can you please try a regular pool like wemineltc and let me know if the problem still persists
2) Do you have a public p2pool node I can use to reproduce this issue? It looks like you submitted a patch to p2pool for working with BFGMiner
3) Can you set me up with SSH access to your machine so I can reproduce the issue there?

Thanks for your help with this.

**Comment by gades** [comment]
1) The problem with other pools appears not as fast as with p2pool (checked on liteguardian.com). See figure performance with the old version bfgminer 
2) My p2pool node is available at the following addresses stratum+tcp:/ /94.100.215.18:9327 or stratum+tcp:/ /176.37.148.85:9327 (this one and the same machine). Said pool is compatibility with older versions - any user name, fixes from Luke-jr to work with new versions bfgminer ( https://github.com/forrestv/p2pool/commit/ce9e5a2b5546a7adac8b686502d78c75ca414e06 ) works with the following logins: msi, iHades and gridseed. (
if self.username == "gridseed" or self.username == "msi" or self.username == "iHades": self.other.svc_mining.rpc_set_difficulty(bitcoin_data.target_to_difficulty(x['share_target'])).addErrback(lambda err: None)
else:
self.other.svc_mining.rpc_set_difficulty(bitcoin_data.target_to_difficulty(x['share_target'])*self.wb.net.DUMB_SCRYPT_DIFF).addErrback(lambda err: None)
)

**Comment by nwoolls** [comment]
@gades I'm not sure what your logs are pulling from: pool-side or client-side, estimated or actual hashes?

There is a bug I just filed a PR for that makes the estimated hash-rates fall low:

https://github.com/luke-jr/bfgminer/pull/515

**Comment by gades** [comment]
The first chart speed pool and in the case of a new code can be seen falling speed after hang-ups, the second graph (cacti) did not show the correct information. Here is an example graph liteguardian.com


I saw # 515 and fixing the schedule turns out not so smooth and displays the actual speed of the device. But I can say with certainty that to version 4.4.0 ustrostvo not hang him and the decision to enter the pool.

**Comment by nwoolls** [comment]
@gades Hopefully I can reproduce the issue. I have a single GSD Orb pointed at your p2pool node. It has been up for 25 minutes so far without any issues. Still submitting shares.

**Comment by nwoolls** [comment]
@gades can you contact me privately with SSH access to your mining rig, or can you use the following site to pinpoint the exact commit that broke things for you?

http://luke.dashjr.org/tmp/code/webisect/webisect.php

Enter anything for the session name (e.g. gades-issue) and then start at 4.4.0 up to the latest commit.

**Comment by gades** [comment]
did not understand what to do next: (I do not need windows build. 
I have to download an archive of the code to merge the problem? and then confirm the presence or absence of a problem? Then I could not find a link to download the archive for linux.

session name - gades-issue

Bisecting: 2 revisions left to test after this (roughly 2 steps)
[59c23461ff4fff4fbeb6351516f258f3eca9b28a] Merge pull request #491 from nwoolls/task/gridseed-remove-sha2

Building 59c23461ff4fff4fbeb6351516f258f3eca9b28a ...
Submodule 'ccan' (git://git.ozlabs.org/~ccan/ccan) registered for path 'ccan-upstream'
Submodule 'libblkmaker' (git://gitorious.org/bitcoin/libblkmaker.git) registered for path 'libblkmaker'
Submodule path 'ccan-upstream': checked out '8b0bdb090e2882aa431e89f4bc7aa4736e9e2838'
Submodule path 'libblkmaker': checked out '6cc0258704ece616f2de6e5509abfc7fba108957'

Builds (log): Win32 | Win64
 Click this only if you are 100% certain that the same bug does not affect this build
 Click this only if you are 100% certain that the same bug affects this build
 Click this if you are uncertain

**Comment by nwoolls** [comment]
@gades I am still trying to reproduce the issue.

In the meantime what I am looking for is either:

1) SSH access to your box or
2) The exact commit that causes the issue for you using git bisect

If you are unable to use the binaries found at http://luke.dashjr.org/tmp/code/webisect/webisect.php you can also try the command line steps listed here:

http://stackoverflow.com/a/4714297/33112

Or, you could clone the repo and check out each commit after 4.4 to try to reproduce the issue, though using git bisect would/should be faster.

I want to make certain that https://github.com/luke-jr/bfgminer/commit/10bfc810948dafaa8fa789700d88b6023bdbcadc specifically is what caused issues for you (there have been other GSD changes since 4.4).

**Comment by gades** [comment]
Bug appeared in this commit, and re-run the test in the event of her, I'll go back and try to 4758bec61205088f4af991b01851232277504fee check for more than 2 hours of time.

**Comment by gades** [comment]
10bfc810948dafaa8fa789700d88b6023bdbcadc is the first bad commit
commit 10bfc810948dafaa8fa789700d88b6023bdbcadc
Author: Nate Woolls nwoolls@gmail.com
Date:   Tue Jul 8 00:25:51 2014 -0400

```
gridseed: Reduce traffic sending work to GridSeed devices

Only send new work to a device when:
There is new work available
Or there is an error reading from the device
Or enough time has passed to scan a full nonce range
```

:100644 100644 ed520579cd920c458b8e30921a3bb892c907a758 fc3a512b95fff0eb8dcb0ea8ea72195d96f60c6d M      driver-gridseed.c
:100644 100644 499bf50d102ea6da57e2ef8ebc160493d2f9a323 5b1af9ba7deb907d7c571f8fd52712496e22b3cf M      gc3355.c
:100644 100644 8123086bb56225c8e8f53e1a8bc4969033327697 ae678990ac7c118f92eb3196196d888bf89c31b6 M      gc3355.h

**Comment by nwoolls** [comment]
Thanks for confirming. I'll take a further look but again I may still need either SSH access or for you to try some modifications to that commit.

I am unable to see any issues with that commit, and I have also run my own GSD hardware against your P2Pool instance for 10 hours now without any issues.

What OS / Hardware are you running on?

**Comment by gades** [comment]
Currently working in version 4758bec61205088f4af991b01851232277504fee [0 days 04:38:03] problems with hanging and I have not found. My OS - Linux ubuntu 14.04 LTS (GNU / Linux 3.13.0-30-generic x86_64). 

It seems to me that the problem is in the timer (! Timer_passed (& tv_nonce_range, NULL). As far as I understand, the gc3355_read (serial_read) has a time out and there is no need in the timer for 10 seconds, or I did not understand the idea of ​​this timer. 

Probably because of this desync with gridseed. May need to implement a wait sequence 0x5520 and it will solve my problem with this type of devices. It is also unclear why the watchdog does not properly reinit.

ps: I use 2 Gridseed G-Blade (one half of the device I broke down)
Bus 005 Device 004: ID 0483:5740 STMicroelectronics STM32F407
Bus 005 Device 003: ID 0483:5740 STMicroelectronics STM32F407
Bus 005 Device 002: ID 0483:5740 STMicroelectronics STM32F407

scan: Found vcom device at dev_t:02a6000000000000 (path=/dev/ttyACM2, vid=0000, pid=0000, manuf=STMicroelectronics, prod=STM32 Virtual COM Port, serial=48E777443838)
scan: Found vcom device at dev_t:01a6000000000000 (path=/dev/ttyACM1, vid=0000, pid=0000, manuf=STMicroelectronics, prod=STM32 Virtual COM Port, serial=48DD8F5A3432)
scan: Found vcom device at dev_t:00a6000000000000 (path=/dev/ttyACM0, vid=0000, pid=0000, manuf=STMicroelectronics, prod=STM32 Virtual COM Port, serial=48DD825C3838)
 [2014-07-16 17:58:35] Acquired exclusive advisory lock on /dev/ttyACM0
 [2014-07-16 17:58:35] Acquired exclusive advisory lock on /dev/ttyACM2
 [2014-07-16 17:58:35] Acquired exclusive advisory lock on /dev/ttyACM1
 [2014-07-16 17:58:36] Found GSD 0 at /dev/ttyACM2
 [2014-07-16 17:58:36] GSD 0: Init: firmware=386077698, chips=40
 [2014-07-16 17:58:36] Found GSD 1 at /dev/ttyACM1
 [2014-07-16 17:58:36] GSD 1: Init: firmware=386077698, chips=40
 [2014-07-16 17:58:36] Found GSD 2 at /dev/ttyACM0
 [2014-07-16 17:58:36] GSD 2: Init: firmware=386077698, chips=40

**Comment by nwoolls** [comment]
There are two timers: one of them simply refreshes the hash-rate every 10 seconds. The other breaks out of the loop once enough time has passed to scan a full nonce range on the device.

The point of the scanhash method is to keep looping reading for nonces until there is new work from the pool. The scanhash method should keep looping, reading from the GridSeed, unless:

1) There is an error reading from the GridSeed
2) Or enough time has passed to scan the full none range based on hash-rate
3) Or new work has arrived and work should be restarted

The old code was basically constantly sending new work to the device, which is a bug.

**Comment by nwoolls** [comment]
@gades Thanks for the details on using a G-Blade. I hooked mine up and was able to reproduce the issue after an hour or so. Stand by.

Also note that, even though I added code to close and re-open the serial file handle, the issue remained after attempted restart.

**Comment by nwoolls** [comment]
@gades thank you again for the feedback. For now I have reverted the commit in 7b2613ec3a4908c9e5d70f2fbe57635ad62c6da4

**Comment by nwoolls** [comment]
@gades If possible, could I get you to test the following branch for me please?

https://github.com/nwoolls/bfgminer/tree/bfgminer-gsd

**Comment by gades** [comment]
I was tested version Luke-jr 65a7398457a858a9a22d5bb3b309d1e7bf21a2d4 (specified version works [0 days 13:05:47] without problems), now make your version 7df575d66f2ed05641424ee36fcaa7059eeb13fa. 
Startup Parameters /opt/bin/bfgminer -scrypt -api-listen -api-network -L / home/hades/bfg30.log - verbose 

bfgminer version 4.4.0-56-g7df575d - Started: [2014-07-22 11:34:15]

**Comment by gades** [comment]
Can control the device from the menu (M) to add a shortcut button - [R]einit?

**Comment by gades** [comment]
Your version does not work (hangs ongoing), the log can be viewed - https://www.dropbox.com/s/2djr1vnf2ajakv3/bfg30.log 

Hung two devices GSD0 & GSD1, recent decisions: 
[2014-07-22 11:43:16] Accepted 0082e5a6 GSD 0bi pool 2 Diff 7m/3m 
[2014-07-22 11:43:14] Accepted 0036f4e8 GSD 1al pool 2 Diff 18m/3m

**Comment by gades** [comment]
Watchdog counters do not work and I have not seen attempts to restart the device.

**Comment by nwoolls** [comment]
@gades that is correct, let me know if the devices hang at all.

**Comment by gades** [comment]
As a result, the dough hanging device 2 of 3. In the log file it shows. May need to do extended logging in problem areas so that you can understand the reason for deadlocks? Such as writing to a file exchange with gridseed or something.

**Comment by nwoolls** [comment]
@gades I have run this build for 14+ hours with no hangs on 4 devices. I'm honestly not sure why you are having trouble with this branch.

**Comment by nwoolls** [comment]
@gades again make sure you are testing the following branch specifically please (not bfgminer-npw):

https://github.com/nwoolls/bfgminer/tree/bfgminer-gsd

e.g.

git clone -b bfgminer-gsd https://github.com/nwoolls/bfgminer.git

**Comment by gades** [comment]
Step 1: git clone https://github.com/nwoolls/bfgminer -b bfgminer-gsd 
Step 2: ./autogen.sh
Step 3: ./configure -prefix /opt/test --enable-scrypt --enable-opencl
Step 4: make
Step 5: make install
Step 6: /opt/test/bin/bfgminer --scrypt --api-listen --api-network -L /home/hades/bfg31.log --verbose
Maybe I incorrectly cloned branch - bfgminer-gsd (I forgot to specify the key-b). The application also collected in a directory for a single.

Now I'm working on this version: bfgminer version 4.4.0-85-g26c388f - Started: [2014-07-22 19:39:32] - [  0 days 00:00:38]

**Comment by gades** [comment]
Hung all 3 devices (left work only OCL)

https://www.dropbox.com/s/b32b7kv9dvbcyic/bfg31.log

Last shares:
[2014-07-22 20:27:14] Accepted 01e79b0b GSD 0az pool 2 Diff 2m/1m
[2014-07-22 20:10:32] Accepted 01611539 GSD 1bj pool 2 Diff 2m/2m
[2014-07-22 20:10:31] Accepted 016792b9 GSD 2az pool 2 Diff 2m/2m
For example OCL:
[2014-07-22 20:49:19] Accepted 0d1eeeca OCL 0  pool 2 Diff 297µ/152µt

**Comment by nwoolls** [comment]
@gades I am unfortunately not able to reproduce this. Please run BFGMiner without a config file and without your backup pools. Use only the following arguments:

```
./bfgminer --scrypt -S noauto -S gsd:all -o stratum+tcp://176.37.148.85:9327 -O LP1SsHZTDexndkvRKsqAkXNsienPHwaMb5:x --set gsd:clock=840 --api-allow 192.168.0.1/24 --api-listen --verbose --verbose-work-updates
```

(replace the LTC address for your own)

I have run the bfgminer-gsd branch against your server 176.37.148.85:9327 for a total of 28 hours (two 14 hour runs) with no hangs.

If this is persisting I really think I'll need access to your machine.

**Comment by nwoolls** [comment]
@gades It would also be helpful if you could bisect which of the 4 commits cause an issue for you:

https://github.com/nwoolls/bfgminer/commits/bfgminer-gsd

**Comment by nwoolls** [comment]
P2Pool Run #1

P2Pool Run #2

These are two 7-hour runs I did against your P2Pool server.

**Comment by nwoolls** [comment]
p.s. Thank you very much for the feedback @gades - we do not want to break anything with this change but the existing driver code is broken / buggy in other ways.

**Comment by nwoolls** [comment]
@gades I have finally reproduced this issue on Debian Linux. I assume this is a timing related issue as BFGMiner determines various timing methods to use based on the OS. I'll get a fix together for that ASAP and get you an updated branch to test.

**Comment by evolvia31** [comment]
Hi, Have you fix this bug because i just have the bug with the 4.7.0 version.
I have 12 G-Blade to a hub and one card hold indefinitely.
The problem appears around 3 or 4 hours after starting bfgminer and the only way to re-launch card is to unplug and plug again usb cable.

**Pull request closed without merging**
