### PR TITLE
Bugfix: probe for ZeusMiner before probing for DualMiner

### PR DESCRIPTION
**Pull request by nwoolls**
Without this, -S all with a DualMiner conflicts with a ZeusMiner

### CODE REVIEW

**Comment by luke-jr** [comment]
"Conflicts" how?

**Comment by nwoolls** [comment]
Causes the Zus not to respond to its own probe

**Comment by luke-jr** [comment]
Won't the Zus probe cause the DualMiner to not respond? :/

**Comment by nwoolls** [comment]
Nope - I tried the various combinations. The only issue is sending the DM probe to the ZM.

**Pull request merged**
