### PR TITLE
Stable Zeus Miner support

### PR DESCRIPTION
**Pull request by jstefanop**
-added support for Zeus scrypt ASICs

### CODE REVIEW

**Comment by nwoolls** [comment]
Hi there. We have started on a clean driver for the ZeusMiner ASICs for BFGMiner. It should be done in a couple of days.

In the future, if you would like to merge in a driver based on the Icarus code, please take a look at the Erupter, AntMiner and DualMiner drivers for ways to do this without copying and modifying the existing Icarus code, which may lead to maintainability issues in the future.

**Comment by jstefanop** [comment]
Great, do you guys have a repo that your working on this? Id love to help out and test...

**Comment by nwoolls** [comment]
Absolutely - I'll share it soon and would appreciate the help and testing.

**Comment by nwoolls** [comment]
Can I get your full name to include in the header for your difficulty fixes?

**Comment by jstefanop** [comment]
sure John Stefanopoulos

**Comment by luke-jr** [comment]
@jstefanop Email address also, for AUTHORS.

**Comment by jstefanop** [comment]
jstefanop at mac com

**Comment by nwoolls** [comment]
Here is the initial work on the ZeusMiner driver - feel free to comment over on my branch, send PRs etc.

https://github.com/nwoolls/bfgminer/commit/506a222715d910267b272d29d9b9eabc7dc8310b

**Comment by jstefanop** [comment]
Closing-  zeusminer support now being worked on nwoolls branch

**Pull request closed without merging**
