### PR TITLE
fix false switching job_switched

### PR DESCRIPTION
**Pull request by alpet83**
Sometimes bits on MISO in Metabank devices lost, and buffer consist abnormal values.

### CODE REVIEW

**Comment by luke-jr** [comment]
d->job_switched should be 0 in this case, not left unchanged, no?

Also, this code is no longer used and will probably be removed soon... Is there still a need for it?

**Comment by alpet83** [comment]
job_switched really changes about one time per second. So code can test values more times per second, and react on true switch. Also you can count the same bits if they are less than 16, the flag should be set.  What alternative detection do you use to change work?

**Comment by luke-jr** [comment]
Using a similar check in bitfury_do_io now, but after checking for SPI corruption (comparing the previous nonce).

**Comment by alpet83** [comment]
Have like solution in https://github.com/alpet83/bfgminer/blob/littlefury/libbitfury.c:811 but check only 16 nonces, and job_switch check separately. Trying to run you last bitfury branch on metabank device, but no chips detected... need new arguments in command line?

**Comment by luke-jr** [comment]
Latest code needs --enable-metabank for configure, and -S metabank:auto for runtime.

**Comment by alpet83** [comment]
Ok. Now it's worked! Please correct help for configure: "--disable-metabank      Compile support for Metabank (default 
disabled)"

**Pull request closed without merging**
