### PR TITLE
Increase usefulness of sharelog by reporting difficulty levels of shares

### PR DESCRIPTION
**Pull request by xrobau**
Add some more information to the sharelog script:

4997200,accept,ffffffffffffffffffffffffffffffffffffffffffffff4b3789410000000000,stratum+tcp://54.206.71.186:9332,PXY16,16,5f844a9c8d58a82f9c050993944a85ebe9d5d02469fdd490f04f2b0000000000,000000027ced44666ce97d508cc41ff9a824192de76a0af72142c9dc0000000000000000aca88457ed4606de7be505675a95e0d9f3f9c2b578333a110db387852a3254925387942018692842dcbd2626000000800000000000000000000000000000000000000000000000000000000000000000000000000000000080020000,1.51k/1k,1513.104908,1000.000000

Note the additional human-readable difficulty, plus the floats of the generated and requested difficulty. This is to ease post-processing of sharelogs later.

### CODE REVIEW

**Comment by luke-jr** [comment]
What is the purpose of logging the "found diff"? It's a meaningless number...?

**Comment by xrobau** [comment]
I added some documentation as to why.  Specifically, some devices have historically had issues submitting higher value shares (specifically, bitmain hardware has been known to be suspiciously unlucky).  It's a useless piece of information UNLESS you want it. In which case it's invaluable, and much easier than calculating it from the sharelog itself.

**Comment by luke-jr** [comment]
Hmm. It's not sufficient to just put the raw float values? :)

**Comment by xrobau** [comment]
The raw float values are there. (last two fields).

**Comment by luke-jr** [comment]
Hence "just"

**Comment by xrobau** [comment]
As I said on IRC, they're there to ease post-processing.  A simple grep/cut/sort is enough to get all the useful information from the file with this patch. Otherwise a complete parser would have to be written.

**Pull request closed without merging**
